const Menu = [
  {
    id: 1,
    images: "https://picsum.photos/id/237/200/300",
    name: "Burger",
    category: "Burger",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Burger, Fast Food, American",
  },

  {
    id: 2,
    images: "https://picsum.photos/id/237/200/300",
    name: "Fish",
    category: "Fish",
    rate: "3.0",
    price: "₹ 200 for",
    description: "Fish, Fast Food, American",
  },
  {
    id: 3,
    images: "https://picsum.photos/id/237/200/300",
    name: "Sandwich",
    category: "Sandwich",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Sandwich Fast Food, American",
  },
  {
    id: 4,
    images: "https://picsum.photos/id/237/200/300",
    name: "Burrito.",
    category: "Burrito",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Burrito, Fast Food, American",
  },
  {
    id: 5,
    images: "https://picsum.photos/id/237/200/300",
    name: "Muffin",
    category: "Muffin",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Muffin, Fast Food, American",
  },
  {
    id: 6,
    images: "https://picsum.photos/id/237/200/300",
    name: "Taco",
    category: "Taco",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Taco., Fast Food, American",
  },
  {
    id: 7,
    images: "https://picsum.photos/id/237/200/300",
    name: "Milkshake",
    category: "Milkshake",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Milkshake., Fast Food, American",
  },
  {
    id: 8,
    images: "https://picsum.photos/id/237/200/300",
    name: "Cheeseburger",
    category: "Cheeseburger",
    rate: "4.0",
    price: "₹ 200 for",
    description: "Cheeseburger., Fast Food, American",
  },
];
export default Menu;
